### ISSUE TITLE
Install broken w/ 63.0 ?

### ISSUE THREAD

**Issue by hgoldwire** [nrobinson2000/homebrew-po#2]
Hi I just found out about this project--looks VERY COOL.  However, install seems busted at the moment.  

After "brew tap nrobinson2000/po" I try "brew install po" and get the following:

☯ brew install po
==> Installing po from nrobinson2000/po
==> Downloading https://github.com/nrobinson2000/homebrew-po/archive/63.0.tar.gz
==> Downloading from https://codeload.github.com/nrobinson2000/homebrew-po/tar.gz/63.0

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "po"
Download failed: https://github.com/nrobinson2000/homebrew-po/archive/63.0.tar.gz

**Comment by nrobinson2000** [comment]
Sorry about that, I'm in the middle of a new release and I actually haven't released 63.0 yet.  I bumped that back down to 62.0 😄 

Try:

```
brew update
brew install po
```

**Comment by hgoldwire** [comment]
Yup, all good now. Thanks!

**Comment by nrobinson2000** [comment]
@hgoldwire I just released 63.0 now.  It is more cleaned up and it has the new `init` command, so you can now create a project with `po init PLATFORM FOLDER`, allowing you to create and initialize new project folders and not just the current working directory.

I hope you enjoy po-util.
