### ISSUE TITLE
Conflict with oh-my-zsh alias `po`

### ISSUE THREAD

**Issue by opyh** [nrobinson2000/homebrew-po#7]
Hi, while installing I stumbled upon the  fact that my [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) installation already comes with an alias `po` for `popd`. While this sounds like a silly issue, many people I know use oh-my-zsh.

What do you think about 
1) an additional check in the installer, maybe something like:
    ```bash
    if [ "`alias po`" != '' ]; then
      echo "WARNING: You already have an alias named 'po'. Use 'unalias po' to remove the alias."
    fi
    ```
2) an alias `po-util` that points to `po`, which is installed per default and is less likely to clash with something?

Without this, it's a bit cryptic to find out what actually happens – `po install` with the set alias just outputs a list of directories.

**Comment by nrobinson2000** [comment]
Thanks for the suggestion. I'll add both features.

**Comment by nrobinson2000** [comment]
I've added the features.  The `po` alias finder is a work in progress, but it should work if the `po` alias is made available via sourcing `~/.bashrc`. You can see it in the installer. https://github.com/nrobinson2000/po/blob/master/install

**Comment by nrobinson2000** [comment]
I reached out to oh-my-zsh maintainers and made a pull request to remove the po alias. This problem should be resolved.
